### ISSUE TITLE
Why is title usbPB

### ISSUE THREAD

**Issue by samiam2013** [Mr-Bossman/usbPB-ThinkPad#1]
I would never ever eat USB flavored peanut butter or pb flavored usb

**Comment by Mr-Bossman** [comment]
I wouldn't either, it just so happens that acronyms overlap.

**Comment by profilelag** [comment]
woah, @Mr-Bossman I would have never guessed

**Comment by samiam2013** [comment]
I literally hate you for resurrecting this thread 
![why](https://media.tenor.com/tDQXUq-HakUAAAAC/why-just-why.gif)
